import { GoogleGenAI } from "@google/genai";

// Initialize the client with the API key from environment variables
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export interface ImageInput {
  data: string; // Base64 string without prefix
  mimeType: string;
}

/**
 * Generates a professional LinkedIn photo based on input images.
 * 
 * @param images Array of source images containing base64 data and mime type.
 * @returns The base64 data URL of the generated image.
 */
export const generateProfessionalPhoto = async (
  images: ImageInput[]
): Promise<string> => {
  try {
    // We use the 2.5 flash image model for efficient image-to-image transformation
    const model = 'gemini-2.5-flash-image';

    const prompt = `
      Act as a professional photographer and photo editor.
      I have provided ${images.length} reference photo(s) of the same person.
      Generate a NEW, high-end professional LinkedIn profile headshot of this person.
      
      Requirements:
      1. IDENTITY: Strictly analyze all provided reference photos to understand the person's facial structure and features. The output MUST look exactly like this person.
      2. ATTIRE: Change the clothing to professional business attire (e.g., a navy blue, charcoal, or black blazer/suit, or professional smart casual). Ensure it fits naturally.
      3. BACKGROUND: Replace the background with a soft-focus, blurred modern office environment or a clean, neutral studio gradient (grey/blue tones).
      4. LIGHTING: Apply soft, flattering studio lighting (rembrandt or butterfly lighting) to enhance the face and remove harsh shadows.
      5. QUALITY: The output must be photorealistic, high resolution, sharp focus on the eyes, and look like it was taken with a DSLR camera (85mm lens style).
      
      Output ONLY the generated image.
    `;

    const imageParts = images.map(img => ({
      inlineData: {
        data: img.data,
        mimeType: img.mimeType,
      },
    }));

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          ...imageParts,
          {
            text: prompt,
          },
        ],
      },
    });

    // Parse the response to find the image part
    let generatedImageUrl: string | null = null;

    if (response.candidates && response.candidates.length > 0) {
      const parts = response.candidates[0].content.parts;
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          generatedImageUrl = `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!generatedImageUrl) {
      throw new Error("No image was generated by the model. Please try a clearer photo or a different angle.");
    }

    return generatedImageUrl;

  } catch (error) {
    console.error("Error generating professional photo:", error);
    throw error;
  }
};